on:
  push:
    paths:
      - data/*
      - scripts/*
      - templates/*
      - Makefile
      - pyproject.toml
      - "*.lock"
jobs:
  UpdateLatestTag:
    name: Publish binaries
    runs-on: ubuntu-latest
    needs: BuildResume
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: "Altair Bueno.zip"
    - name: Upload resume to `latest`
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: resume.pdf
        tag: latest
        asset_name: resume.pdf
        overwrite: true
  BuildResume:
    runs-on: macos-latest # Should have Arial installed
    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Config poetry
        run: |
          poetry env use "3.10"

      - name: Install BasicTex
        run: |
          brew install --cask basictex
          echo "/Library/TeX/texbin/" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          make deps

      - name: Build resume
        run: make
      
      # Upload artifacts
      - name: Upload resume
        uses: actions/upload-artifact@v2
        with:
          name: "Altair Bueno.zip"
          path: out/resume.pdf
