on:
  push:
    branches:
      - "*"

jobs:
  BuildResume:
    runs-on: macos-latest # Should have Arial installed
    steps:
      - uses: actions/checkout@v2

      - name: Install required software
        run: |
          brew install --cask basictex
          echo "/Library/TeX/texbin/" >> $GITHUB_PATH
          brew install poetry

      - name: Install dependencies
        run: |
          make deps

      - name: Build resume
        run: make
      
      # Upload artifacts
      - name: Upload resume
        uses: actions/upload-artifact@v2
        with:
          name: "Altair Bueno.zip"
          path: out/resume.pdf
