on:
  push:
    branches:
      - master
env:
  _PYTHON_VERSION: "3.11"
jobs:
  UpdateLatestTag:
    name: Publish binaries
    runs-on: ubuntu-latest
    needs: BuildResume
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "Altair Bueno.zip"
      - name: Upload resume to `latest`
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: resume.pdf
          tag: latest
          asset_name: resume.pdf
          overwrite: true
  UpdateThumbnail:
    name: Update thumbnail
    runs-on: ubuntu-latest
    needs: BuildResume
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install poppler-utils
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env._PYTHON_VERSION }}
          cache: "pip"
      - uses: actions/download-artifact@v3
        with:
          name: "Altair Bueno.zip"
          path: out/
      - name: Install
        run: make deps/python
      - name: Create thumbnail
        run: make thumbnail
      - name: Upload changes
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add --all
          git commit -am "Actions: Updated thumbnail"
          git push
  BuildResume:
    runs-on: macos-latest # Should have Arial installed
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.12.0

      - name: Build resume
        run: make

      # Upload artifacts
      - name: Upload resume
        uses: actions/upload-artifact@v2
        with:
          name: "Altair Bueno.zip"
          path: out/resume.pdf
