on:
  push:
    branches:
      - "*"
    tags:
      - "*"

permissions:
  packages: write
  contents: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - run: deno fmt --check

  build:
    runs-on: ubuntu-latest
    needs:
      - fmt
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - uses: wtfjoke/setup-tectonic@v3
      - name: Install apt packages
        run: apt-get update && apt-get install -y poppler-utils
      - run: make resume thumbnail
      - uses: actions/upload-artifact@v4
        with:
          path: out/resume.pdf
      - uses: actions/upload-artifact@v4
        with:
          path: out/thumbnail.png
      - uses: elgohr/Github-Release-Action@v5
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
