on:
  push:
    branches:
      - "*"
    tags:
      - "*"

permissions:
  packages: write
  contents: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - run: deno fmt --check

  build:
    runs-on: ubuntu-latest
    needs:
      - fmt
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - uses: wtfjoke/setup-tectonic@v3
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: poppler-utils
          version: 1.0
      - run: make resume thumbnail
      - uses: actions/upload-artifact@v4
        with:
          path: out/resume.pdf
          name: resume
      - uses: actions/upload-artifact@v4
        with:
          path: out/thumbnail.png
          name: thumbnail
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || (github.ref == 'refs/heads/master')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          files: |
            out/resume.pdf
            out/thumbnail.png
