on:
  push:
    branches:
      - "*"
    tags:
      - "*"

permissions:
  packages: write
  contents: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - run: deno fmt --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - uses: wtfjoke/setup-tectonic@v3
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.5.0
        with:
          packages: poppler-utils
          version: 1.0
      - run: make resume thumbnail
      - uses: actions/upload-artifact@v4
        with:
          path: out/resume.pdf
          name: resume
      - uses: actions/upload-artifact@v4
        with:
          path: out/thumbnail.png
          name: thumbnail
  ci-check:
    name: Check all statuses are green
    if: always()
    needs:
      - fmt
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    if: >
      startsWith(github.ref, 'refs/heads/main')
      || startsWith(github.ref, 'refs/heads/master')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: out/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
